name: Json sender
on:
  workflow_call:
          
    
jobs:
  send_notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send test notify message
        run: |
          curl -X POST ${{ vars.TELEGRAM_CHME_REPORTS_PATH }} \
          -H "Content-Type: application/json" \
          -d '{"message": "test notify"}'

