name: Json sender
on:
  workflow_call:
          
    
jobs:
  send_notify:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare JSON
        run: |
          JSON_PAYLOAD=$(echo '{
            "repository": "'"${{ github.repository }}"'",
            "workflow": "'"${{ github.workflow }}"'",
            "run_id": "'"${{ github.run_id }}"'",
            "run_url": "'"${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"'",
            "message": "GitHub Workflow Notification: Workflow '\''${{ github.workflow }}'\'' from repository '\''${{ github.repository }}'\'' failed. View details at: '\''${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'\''
          }')
          echo "$JSON_PAYLOAD" > output.json

      - name: debug JSON
        run: |
          echo "Contents of output.json:"
          cat output.json

      - name: Send test notify message
        run: |
          curl -X POST https://qqqqqqqqqq.q \
          -H "Content-Type: application/json" \
          -d '{"message": "test notify"}'

