name: Env variables and secret usage
on:
  workflow_dispatch

jobs:
  work_with_var:
    runs-on: ubuntu-latest
    environment: "PROD"
    env:
      REPO_SEC_PASS: ${{ secrets.REPO_SEC_PASS }}
      PROD_SEC_PASS: ${{ secrets.PROD_SEC_PASS }}
      PROD_HOST_PATH: ${{ vars.PROD_HOST_PATH }}
    steps:
      - name: print repo secrets 
        run: echo "$REPO_SEC_PASS"

      - name: print prod secrets
        run: echo "$PROD_SEC_PASS"

      - name: print prod env variable
        run: echo "$PROD_HOST_PATH"